### ISSUE TITLE
TTL/SSL Issues

### ISSUE THREAD

**Issue by afinzel** [paypal/sdk-core-dotnet#46]
With https://github.com/paypal/sdk-core-dotnet/commit/da69b7c5cf4be6de848a8ebdde1f02168c211165 I added some comments.  It looks like you have fixed them on https://github.com/paypal/PayPal-NET-SDK/commit/d497682b469815726301b24d7a9e973b079d0f1d but shouldn't these be also ported on to this?

**Comment by wakm** [comment]
**BE AWARE OF VERSION 1.7.0 - CHANGES EFFECT GLOBAL BEHAVIOR OF WEB APPLICATION**
Please notify about this **important** changes your costumers who use version 1.7.0 since this break the ssl default behavior of .net AND enforce  SecurityProtocolType.Tls12 for ALL connections. 

Everybody should update to version 1.7.1!

@afinzel you are right. your comments must be ported!

**Comment by jziaja** [comment]
@afinzel yes, you are correct.  The [new fix in 1.7.1](https://github.com/paypal/sdk-core-dotnet/blob/v1.7.1/Source/SDK/Manager/ConnectionManager.cs#L68) updates the support for TLSv1.2 so it also allows for default fallback behavior.

**Comment by afinzel** [comment]
Thanks
